- hosts: all
  gather_facts: true
  become_method: sudo
  become_user: root
  tasks:
    - name: update openssl from apt if available
      apt:
        name: openssl
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'
      notify: restart_system

    - name: update openssl from yum if available
      yum:
        name: openssl
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat'
      notify: restart_system

  handlers:
    - name: restart_system
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
